name: Publish Package to npm
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Update npm
        run: npm install -g npm@latest
      - name: Run npm ci
        run: npm ci
      - name: Build lib
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Verify ESLint
        run: npx eslint src/**/*.ts
      - name: Determine version type
        id: version_type
        run: |
          if [[ ${{ github.event.release.tag_name }} == *"-beta"* ]] || [[ ${{ github.event.release.tag_name }} == *"-rc"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
      - name: Publish prerelease version
        if: steps.version_type.outputs.is_prerelease == 'true'
        run: |
          if [[ ${{ github.event.release.tag_name }} == *'-beta'* ]]; then
            npm publish --provenance --tag beta
          else
            npm publish --provenance --tag rc
          fi
      - name: Publish stable version
        if: steps.version_type.outputs.is_prerelease == 'false'
        run: npm publish --provenance --access public
